services:
  # Base de Datos Relacional PostgreSQL
  postgres-db:
    image: postgres:15-alpine
    container_name: innovatech-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: innovatech_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: supersecretpassword
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Microservicio de Autenticación
  ms-auth:
    build: ./innovatech-ms-autenticacion
    container_name: ms-auth
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/innovatech_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: supersecretpassword
      JWT_SECRET: innovatech2026_fullstack3_RichardMoreano
    depends_on:
      - postgres-db

  # Microservicio de Gestión de Proyectos
  ms-gestion-proyectos:
    build: ./innovatech-ms-gestion-proyectos
    container_name: ms-gestion-proyectos
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/innovatech_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: supersecretpassword
    depends_on:
      - postgres-db

  # Microservicio de Gestión de Recursos
  ms-gestion-recursos:
    build: ./innovatech-ms-gestion-recursos
    container_name: ms-gestion-recursos
    ports:
      - "8086:8086"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/innovatech_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: supersecretpassword
    depends_on:
      - postgres-db

  # Microservicio de Monitoreo y Analítica
  ms-monitoreo-analitica:
    build: ./innovatech-ms-monitoreo-analitica
    container_name: ms-monitoreo-analitica
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/innovatech_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: supersecretpassword
    depends_on:
      - postgres-db

  # Capa Intermedia Compuesta (BFF)
  innovatech-bff:
    build: ./innovatech-bff
    container_name: innovatech-bff
    ports:
      - "8080:8080"
    environment:
      JWT_SECRET: innovatech2026_fullstack3_RichardMoreano
      # Inyecciones de red internas para comunicación inter-contenedor
      PROYECTOS_URL: http://ms-gestion-proyectos:8081
      RECURSOS_URL: http://ms-gestion-recursos:8086
      MONITOREO_URL: http://ms-monitoreo-analitica:8084
    depends_on:
      - ms-gestion-proyectos
      - ms-gestion-recursos
      - ms-monitoreo-analitica

  # Puerta de Entrada Única (API Gateway)
  api-gateway:
    build: ./innovatech-api-gateway
    container_name: api-gateway
    ports:
      - "8083:8083"
    environment:
      AUTH_SERVICE_URL: http://ms-auth:8082
      BFF_SERVICE_URL: http://innovatech-bff:8080
      JWT_SECRET: innovatech2026_fullstack3_RichardMoreano
    depends_on:
      - ms-auth
      - innovatech-bff

  # Interfaz de Usuario
  innovatech-frontend:
    build: ./innovatech-frontend
    container_name: innovatech-frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8083
    depends_on:
      - api-gateway

volumes:
  pgdata: