version: '3.8'

services:
  # ==========================================
  # BASE DE DATOS CONTENEDORIZADA
  # ==========================================
  postgres-db:
    image: postgres:15-alpine
    container_name: innovatech-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: innovatech_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: supersecretpassword
    volumes:
      - pgdata:/var/lib/postgresql/data

  # ==========================================
  # MICROSERVICIOS DE NEGOCIO (BACKEND V2)
  # ==========================================
  ms-auth:
    build: ./innovatech-ms-autenticacion # <-- Ajustado a tu carpeta real
    container_name: ms-auth
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/innovatech_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: supersecretpassword
      JWT_SECRET: innovatech2026_fullstack3_RichardMoreano
    depends_on:
      - postgres-db

  ms-gestion-proyectos:
    build: ./innovatech-ms-gestion-proyectos # <-- Ajustado a tu carpeta real
    container_name: ms-gestion-proyectos
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/innovatech_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: supersecretpassword
    depends_on:
      - postgres-db

  # ==========================================
  # CAPA COMPUESTA (BFF CSR)
  # ==========================================
  innovatech-bff:
    build: ./innovatech-bff # <-- Coincide con tu carpeta real
    container_name: innovatech-bff
    ports:
      - "8080:8080"
    environment:
      PROYECTOS_URL: http://ms-gestion-proyectos:8081
      JWT_SECRET: innovatech2026_fullstack3_RichardMoreano
    depends_on:
      - ms-gestion-proyectos

  # ==========================================
  # PUERTA DE ENTRADA (API GATEWAY CENTRAL)
  # ==========================================
  api-gateway:
    build: ./innovatech-api-gateway # <-- Ajustado a tu carpeta real
    container_name: api-gateway
    ports:
      - "8083:8083"
    environment:
      AUTH_SERVICE_URL: http://ms-auth:8082
      BFF_SERVICE_URL: http://innovatech-bff:8080
      JWT_SECRET: innovatech2026_fullstack3_RichardMoreano
    depends_on:
      - ms-auth
      - innovatech-bff

  # ==========================================
  # INTERFAZ DE USUARIO (FRONTEND NEXT.JS)
  # ==========================================
  innovatech-frontend:
    build: ./innovatech-frontend # <-- Coincide con tu carpeta real
    container_name: innovatech-frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8083/api/v2
    depends_on:
      - api-gateway

volumes:
  pgdata: